# Generated by Django 4.1.5 on 2023-03-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('telefono', models.CharField(max_length=55)),
                ('mail', models.EmailField(max_length=55)),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
    ]
